/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base.de.conocimiento;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jpl7.Term;

/**
 *
 * @author LUISF
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public Main() {
        bdc = new BaseDeConocimiento();
        initComponents();
         jldescription.setText("");
        jlclasificacion.setText("");
        setLocationRelativeTo(null);
        jbSearch.requestFocus();
        setIconImage(Toolkit.getDefaultToolkit().getImage("animals/logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbSearch = new javax.swing.JButton();
        jlImage = new javax.swing.JLabel();
        jlname = new javax.swing.JLabel();
        jlclas = new javax.swing.JLabel();
        jlclasificacion = new javax.swing.JLabel();
        jlcar = new javax.swing.JLabel();
        jlyear = new javax.swing.JLabel();
        jbRandom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jldescription = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zoopedia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 246, 212));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUISF\\Documents\\NetBeansProjects\\Zoopedia\\animals\\background.png")); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 370));

        jLayeredPane2.setMaximumSize(new java.awt.Dimension(32767, 100));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(419, 200));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUISF\\Documents\\NetBeansProjects\\Zoopedia\\animals\\logo.png")); // NOI18N
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Escriba el nombre de un animal...");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jbSearch.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jbSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUISF\\Documents\\NetBeansProjects\\Zoopedia\\animals\\search.png")); // NOI18N
        jbSearch.setText("Buscar");
        jbSearch.setBorderPainted(false);
        jbSearch.setContentAreaFilled(false);
        jbSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSearchMouseExited(evt);
            }
        });
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        jlImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlname.setBackground(new java.awt.Color(255, 255, 255));
        jlname.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jlname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlclas.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jlclas.setText("Clasificación:");

        jlclasificacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlclasificacion.setText("text");

        jlcar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jlcar.setText("Características:");

        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlImage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlclas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlclasificacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlcar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                            .addGap(0, 84, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbSearch)
                            .addGap(53, 53, 53))
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                            .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 240, Short.MAX_VALUE)))
                    .addContainerGap()))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(jlclas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jlclasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(jlcar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSearch))
                    .addGap(38, 38, 38)
                    .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jlclas)
                    .addContainerGap(275, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(241, Short.MAX_VALUE)
                    .addComponent(jlclasificacion)
                    .addGap(257, 257, 257)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(258, Short.MAX_VALUE)
                    .addComponent(jlcar)
                    .addGap(240, 240, 240)))
        );

        jlyear.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlyear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlyear.setText("v1.0.0 2022 ");

        jbRandom.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jbRandom.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUISF\\Documents\\NetBeansProjects\\Zoopedia\\animals\\random.png")); // NOI18N
        jbRandom.setText("Aleatorio");
        jbRandom.setContentAreaFilled(false);
        jbRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRandomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRandomMouseExited(evt);
            }
        });
        jbRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRandomActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jldescription.setBackground(new java.awt.Color(255, 246, 212));
        jldescription.setColumns(20);
        jldescription.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jldescription.setLineWrap(true);
        jldescription.setRows(5);
        jScrollPane1.setViewportView(jldescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbRandom))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 319, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jbRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlyear, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Info");

        jMenuItem1.setText("A cerca de...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        aparienceTF();
        if (!jTextField1.getText().trim().equals("")) {
            try {
                Map<String, Term> c = bdc.consulta(jTextField1.getText());
                String animal = jTextField1.getText().trim().toLowerCase();
                String d = c.get("D").toString().replace("[", "").replace("]", ".").replaceAll("'", "");
                d = d.replaceFirst(d.substring(0, 1), d.substring(0, 1).toUpperCase());
                String tipo = c.get("T").toString().replace("'", "");
                System.out.println(tipo);
                String caract = c.get("C").toString().replace("'", "");

                jlname.setText(animal.replaceFirst(animal.substring(0, 1), animal.substring(0, 1).toUpperCase()));
                jldescription.setText(d);
                jlclasificacion.setText("Es un " + tipo.replace("_", " ") + " " + caract + ".");

                jlImage.setIcon(new ImageIcon("filo/" + tipo + "/" + spacialChar(animal) + ".png"));
                try {
                    BufferedImage bf = ImageIO.read(new File("filo/" + tipo + "/" + animal + ".png"));
                Color color = new Color(bf.getRGB(bf.getWidth()/2, bf.getHeight()/2));
                if (color .getRGB() > -924188)
                {System.out.println(color.getRGB());
                    color  = Color.BLACK;
                    System.out.println("color");
                }
                    jlname.setForeground(color );
                } catch (IOException ex) {
                    System.out.println("No se encontro foto");
                }
            } catch (NoEncontradoException ex) {
                
                jlname.setText("Animal no encontrado.");
                jldescription.setText("");
                jlclasificacion.setText("");
                jlImage.setIcon(new ImageIcon("filo/no encontrado.png"));
                System.out.println("No encontro ningun animal");
            }
        }
    }//GEN-LAST:event_jbSearchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new jdInfo(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSearchMouseEntered
     jbSearch.setForeground(new Color(0xffcc00));
    }//GEN-LAST:event_jbSearchMouseEntered

    private void jbSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSearchMouseExited
        jbSearch.setForeground(new Color(0x000000));
    }//GEN-LAST:event_jbSearchMouseExited
 private String spacialChar(String text){
        char []sc = {'á','é','í','ó','ù'};
        char [] c = {'a','e','i','o','o'};
        
        for (int i = 0; i < c.length; i++) {
            text = text.replace(sc[i], c[i]);
        }
        System.out.println(text);
        return text;
    }
    private void jbRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRandomActionPerformed
        aparienceTF();  
        Map<String, Term> c = bdc.random();
            String animal = c.get("N").toString().replaceAll("'", "");
            String d = c.get("D").toString().replace("[", "").replace("]", ".").replaceAll("'", "");
            d = d.replaceFirst(d.substring(0, 1), d.substring(0, 1).toUpperCase());
            String tipo = c.get("T").toString().replace("'", "");
            System.out.println(tipo);
            String caract = c.get("C").toString().replace("'", "");
            jlname.setText(animal.replaceFirst(animal.substring(0, 1), animal.substring(0, 1).toUpperCase()));
            jldescription.setText(d);
            jlclasificacion.setText("Es un " + tipo.replace("_", " ") + " " + caract + ".");
            jlImage.setIcon(new ImageIcon("filo/" + tipo + "/" + spacialChar(animal) + ".png"));
            try {
                BufferedImage bf = ImageIO.read(new File("filo/" + tipo + "/" + animal + ".png"));
                Color color = new Color(bf.getRGB(bf.getWidth()/2, bf.getHeight()/2));
                if (color .getRGB() > -924188){
                    System.out.println(color.getRGB());
                    color  = Color.BLACK;
                }
                jlname.setForeground(color );
            } catch (IOException ex) {
                System.out.println("No se encontró");
            }
    }//GEN-LAST:event_jbRandomActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if (!jTextField1.getForeground().equals(Color.BLACK)){
            jTextField1.setForeground(Color.BLACK);
            jTextField1.setText("");
       }else{
            jTextField1.setText("");
        }
        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jbRandomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRandomMouseEntered
       jbRandom.setForeground(new Color(0xffcc00));
    }//GEN-LAST:event_jbRandomMouseEntered

    private void jbRandomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRandomMouseExited
 jbRandom.setForeground(new Color(0x000000));
    }//GEN-LAST:event_jbRandomMouseExited

    private void aparienceTF(){
        if (jTextField1.getText().trim().equals("")){
            jTextField1.setText("Escriba el nombre de un animal...");
            jTextField1.setForeground(new Color(153,153,153));
        }
            
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbRandom;
    private javax.swing.JButton jbSearch;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlcar;
    private javax.swing.JLabel jlclas;
    private javax.swing.JLabel jlclasificacion;
    private javax.swing.JTextArea jldescription;
    private javax.swing.JLabel jlname;
    private javax.swing.JLabel jlyear;
    // End of variables declaration//GEN-END:variables
    private final BaseDeConocimiento bdc;
}
